def get_currency_and_rates(country: str):
    data = {
        "India": {"currency": "INR", "usd_rate": 83.0},
        "United States": {"currency": "USD", "usd_rate": 1.0},
        "Japan": {"currency": "JPY", "usd_rate": 148.0},
        "United Kingdom": {"currency": "GBP", "usd_rate": 0.78},
        "European Union": {"currency": "EUR", "usd_rate": 0.92},
        "China": {"currency": "CNY", "usd_rate": 7.2},
        "Canada": {"currency": "CAD", "usd_rate": 1.35},
        "Australia": {"currency": "AUD", "usd_rate": 1.52},
        "New Zealand": {"currency": "NZD", "usd_rate": 1.63},
        "South Korea": {"currency": "KRW", "usd_rate": 1330.0},
        "Russia": {"currency": "RUB", "usd_rate": 92.0},
        "Brazil": {"currency": "BRL", "usd_rate": 5.0},
        "South Africa": {"currency": "ZAR", "usd_rate": 18.5},
        "Mexico": {"currency": "MXN", "usd_rate": 17.0},
        "Singapore": {"currency": "SGD", "usd_rate": 1.34},
        "Malaysia": {"currency": "MYR", "usd_rate": 4.7},
        "Indonesia": {"currency": "IDR", "usd_rate": 15500.0},
        "Thailand": {"currency": "THB", "usd_rate": 36.0},
        "Philippines": {"currency": "PHP", "usd_rate": 56.0},
        "Vietnam": {"currency": "VND", "usd_rate": 24500.0},
        "Pakistan": {"currency": "PKR", "usd_rate": 278.0},
        "Bangladesh": {"currency": "BDT", "usd_rate": 110.0},
        "Sri Lanka": {"currency": "LKR", "usd_rate": 310.0},
        "Nepal": {"currency": "NPR", "usd_rate": 133.0},
        "UAE": {"currency": "AED", "usd_rate": 3.67},
        "Saudi Arabia": {"currency": "SAR", "usd_rate": 3.75},
        "Qatar": {"currency": "QAR", "usd_rate": 3.64},
        "Israel": {"currency": "ILS", "usd_rate": 3.7},
        "Turkey": {"currency": "TRY", "usd_rate": 30.0},
        "Iran": {"currency": "IRR", "usd_rate": 42000.0},
        "Egypt": {"currency": "EGP", "usd_rate": 30.9},
        "Nigeria": {"currency": "NGN", "usd_rate": 1500.0},
        "Kenya": {"currency": "KES", "usd_rate": 160.0},
        "Argentina": {"currency": "ARS", "usd_rate": 900.0},
        "Chile": {"currency": "CLP", "usd_rate": 950.0},
        "Colombia": {"currency": "COP", "usd_rate": 3950.0},
        "Peru": {"currency": "PEN", "usd_rate": 3.7},
        "Switzerland": {"currency": "CHF", "usd_rate": 0.88},
        "Sweden": {"currency": "SEK", "usd_rate": 10.4},
        "Norway": {"currency": "NOK", "usd_rate": 10.6},
        "Denmark": {"currency": "DKK", "usd_rate": 6.9},
        "Poland": {"currency": "PLN", "usd_rate": 4.0},
        "Czech Republic": {"currency": "CZK", "usd_rate": 23.0},
        "Hungary": {"currency": "HUF", "usd_rate": 360.0},
        "Ukraine": {"currency": "UAH", "usd_rate": 38.0},
    }

    return data.get(country, {"error": "Country not supported"})
