def get_exchange_and_index(country: str):
    data = {
        "India": {"exchange": "NSE/BSE", "index": "NIFTY 50"},
        "United States": {"exchange": "NYSE/NASDAQ", "index": "S&P 500"},
        "Japan": {"exchange": "TSE", "index": "Nikkei 225"},
        "United Kingdom": {"exchange": "LSE", "index": "FTSE 100"},
        "China": {"exchange": "SSE/SZSE", "index": "CSI 300"},
        "Hong Kong": {"exchange": "HKEX", "index": "Hang Seng"},
        "Germany": {"exchange": "Frankfurt", "index": "DAX"},
        "France": {"exchange": "Euronext Paris", "index": "CAC 40"},
        "Italy": {"exchange": "Borsa Italiana", "index": "FTSE MIB"},
        "Spain": {"exchange": "BME Madrid", "index": "IBEX 35"},
        "Canada": {"exchange": "TSX", "index": "S&P/TSX Composite"},
        "Australia": {"exchange": "ASX", "index": "ASX 200"},
        "South Korea": {"exchange": "KRX", "index": "KOSPI"},
        "Taiwan": {"exchange": "TWSE", "index": "TAIEX"},
        "Singapore": {"exchange": "SGX", "index": "STI"},
        "Malaysia": {"exchange": "Bursa Malaysia", "index": "FTSE Bursa Malaysia KLCI"},
        "Indonesia": {"exchange": "IDX", "index": "IDX Composite"},
        "Thailand": {"exchange": "SET", "index": "SET Index"},
        "Philippines": {"exchange": "PSE", "index": "PSEi"},
        "Vietnam": {"exchange": "HOSE", "index": "VN-Index"},
        "Pakistan": {"exchange": "PSX", "index": "KSE-100"},
        "Bangladesh": {"exchange": "DSE", "index": "DSEX"},
        "Sri Lanka": {"exchange": "CSE", "index": "ASPI"},
        "Nepal": {"exchange": "NEPSE", "index": "NEPSE Index"},
        "UAE": {"exchange": "DFM/ADX", "index": "DFM General Index"},
        "Saudi Arabia": {"exchange": "Tadawul", "index": "TASI"},
        "Qatar": {"exchange": "QSE", "index": "QE Index"},
        "Israel": {"exchange": "TASE", "index": "TA-35"},
        "Turkey": {"exchange": "Borsa Istanbul", "index": "BIST 100"},
        "Russia": {"exchange": "MOEX", "index": "MOEX Russia Index"},
        "South Africa": {"exchange": "JSE", "index": "FTSE/JSE All Share"},
        "Nigeria": {"exchange": "NGX", "index": "NGX All-Share"},
        "Kenya": {"exchange": "NSE Kenya", "index": "NSE 20"},
        "Egypt": {"exchange": "EGX", "index": "EGX 30"},
        "Brazil": {"exchange": "B3", "index": "Ibovespa"},
        "Argentina": {"exchange": "BYMA", "index": "MERVAL"},
        "Mexico": {"exchange": "BMV", "index": "IPC"},
        "Chile": {"exchange": "BCS", "index": "IPSA"},
        "Colombia": {"exchange": "BVC", "index": "COLCAP"},
        "Peru": {"exchange": "BVL", "index": "S&P/BVL General"},
        "Switzerland": {"exchange": "SIX", "index": "SMI"},
        "Sweden": {"exchange": "Nasdaq Stockholm", "index": "OMX Stockholm 30"},
        "Norway": {"exchange": "Oslo Børs", "index": "OSEBX"},
        "Denmark": {"exchange": "Nasdaq Copenhagen", "index": "OMXC25"},
        "Poland": {"exchange": "WSE", "index": "WIG20"},
        "Czech Republic": {"exchange": "PSE", "index": "PX Index"},
        "Hungary": {"exchange": "BSE Budapest", "index": "BUX"},
        "Ukraine": {"exchange": "UX Exchange", "index": "UX Index"},
    }

    return data.get(country, {"error": "Country not supported"})
